name: 'tests'

on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: "basic"
    runs-on: 'ubuntu-latest'
    container: 'registry.suse.com/bci/python:3.11'

    steps:
      - name: 'Install packages'
        run: |
            zypper -n install python311-pydantic python311-pytest python311-setuptools python311-rpm python311-PyYAML

      - uses: actions/checkout@v4

      - name: 'Run basic example verification'
        run: |
          python3 -m venv venv --system-site-packages
          source venv/bin/activate
          pip install --no-dependencies -e .
          productcomposer verify examples/ftp.productcompose
#          pytest tests
